title: "Ajeet Singh Yadav"
description: "Senior Software Engineer | Robotics | Graphics | Game Engines"
url: "https://ajeetsinghyadav.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "sunrise" # Try a more colorful skin

# Site settings
locale: "en-US"
repository: "ajeetsinghyadav/ajeetsinghyadav.github.io"

# Site Author
author:
  name: "Ajeet Singh Yadav"
  avatar: "/assets/images/avatar.png"
  bio: "Senior Software Engineer at Stryker, specializing in robotics, 3D visualization, and game engine development."
  location: "Weston, FL"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:yadav.ajeetsingh2020@email.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ajeetsinghyadav"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ajeet-yadav-b1133991"

# Social sharing
twitter:
  username: "your_twitter_username"
github:
  username: "ajeetsinghyadav"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache

# Collections for custom pages
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: single
      author_profile: true


# Other settings
markdown: kramdown
highlighter: rouge

# Force GitHub Pages Rebuild
