title: "ajeetsinghyadav.github.io"
description: "An amazing website."
url: "https://ajeetsinghyadav.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
locale: "en-US"
repository: "ajeetsinghyadav/ajeetsinghyadav.github.io"

# Site Author
author:
  name: "Ajeet Singh Yadav"
  avatar: "/assets/images/avatar.png"
  bio: "I am a Senior Staff Software Engineer in Stryker with over 10 years of experience."
  location: "Weston, FL"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:yadav.ajeetsingh2020@email.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ajeetsinghyadav"

# Social sharing
twitter:
  username: "your_twitter_username"
github:
  username: "ajeetsinghyadav"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache

# Other settings
markdown: kramdown
highlighter: rouge
